### ISSUE TITLE
How to compute inner product of two stablizer states?

### ISSUE THREAD

**Issue by ChenZhao44** [Krastanov/QuantumClifford.jl#26]
Hi, I want to use this package to simulate Clifford circuits. And I want to know how to compute the inner product of two stablizer states with this package.

**Comment by Krastanov** [comment]
Hello, @ChenZhao44 ,

Good point, this should be included! This reference shows how to do an inner product of tableaux https://arxiv.org/pdf/1210.6646.pdf

I wrote an [implementation](https://krastanov.github.io/QuantumClifford.jl/dev/API/#QuantumClifford.logdot-Tuple{QuantumClifford.AbstractStabilizer,%20QuantumClifford.AbstractStabilizer}) for it [today](https://github.com/Krastanov/QuantumClifford.jl/commit/6eebaba54bf5a594a04ed320c3d581aae2edcb4b), but I would prefer not to make a release version yet, until it is tested a bit better. If you would like, you can install a development version that includes this new feature with `] add QuantumClifford#master`. If you end up using it, I would be interested in hearing from you, whether it fits your use case.

Also, most of the library is written to study dense tableaux, so it still lacks some features related to working with single small Clifford operations. You would probably want to use https://krastanov.github.io/QuantumClifford.jl/dev/manual/#Small-Symbolic-Clifford-Operators and deal with projection/measurement operations separately (probably by using [`project!`](https://krastanov.github.io/QuantumClifford.jl/dev/manual/#Projective-Measurements) and [`single_x/y/z`](https://krastanov.github.io/QuantumClifford.jl/dev/API/#QuantumClifford.single_x-Tuple{Any,%20Any})). Do let me know what you feel is missing from the library for your use case, as it might differ from how others are using it. Of course, functionality and documentation pull requests are always welcome.

**Comment by ChenZhao44** [comment]
@Krastanov Thanks for your help! 
I'm trying to develop a package to integrate QuantumClifford with [Yao](https://github.com/QuantumBFS/Yao.jl). This function is really useful.

**Comment by Krastanov** [comment]
This is great news! Yao is great but its style does not always match the assumptions in this library, so feel free to submit a plethora of issues here when it seems like this library requires you to write code in a convoluted way. I would like to clean up the API so things are easier. Given your use case you will probably encounter performance bugs as well, so feel free to submit issues about those as well (this library is supposed to be multi-threaded and mostly allocation free). In particular, tensor products of tableaux are rather slow right now and it is something I would like to change.

**Comment by Krastanov** [comment]
closing as this will be in the 0.3.0 to be release shortly
