### ISSUE TITLE
Expectation of Pauli string on stabilizer states

### ISSUE THREAD

**Issue by ChenZhao44** [Krastanov/QuantumClifford.jl#29]
This feature is useful for simulating Clifford circuit. I am trying to implement one.

**Comment by Krastanov** [comment]
`project!(copy(stabilizer_state), pauli)` is probably going to get you 90% there. https://krastanov.github.io/QuantumClifford.jl/dev/manual/#Projective-Measurements

**Comment by Krastanov** [comment]
And this explains how expensive different implementations of that operation are https://krastanov.github.io/QuantumClifford.jl/dev/datastructures/#Choosing-Appropriate-Data-Structure

**Comment by ChenZhao44** [comment]
@Krastanov I created a PR #30

**Comment by Krastanov** [comment]
Merged #30
