### ISSUE TITLE
higher test coverage

### ISSUE THREAD

**Issue by Krastanov** [Krastanov/QuantumClifford.jl#43]
The test coverage is only 80%. While it covers most of the "math" algorithms, it does not cover well the various warnings and error messages raised on inconsistent input. Both can be improved (but improving the `Experimental` modules is not worth it yet).

**Comment by anonymousr007** [comment]
Hello @Krastanov, I am Rishabh, an undergraduate final year computer engineering student. I want to work on this issue, Can you please more elaborate about this issue?

**Comment by Krastanov** [comment]
Hi, Rishabh. In test-coverage tools like https://app.codecov.io/gh/Krastanov/QuantumClifford.jl/blob/master/src/QuantumClifford.jl (for one particular file) you can see parts of the code base that are not tested. In particular, parts of the code that are if/else branches in long functions that are not invoked by tests. To ensure future changes to the code do not break something it is useful to make sure such "test misses" are covered, by writing test sets for them. The aforementioned file (where marked with red) is a good place to start. It would be a good idea to have a rough understanding of the library before you start.

**Comment by anonymousr007** [comment]
Something awesome, this will help me to understand the entire codebase (for GSOC) in such an awesome manner. I would like to tell you to, I want to work on this issue. Can you please assign me this issue? and I have a question I will do this with every single file? Right?

**Comment by Krastanov** [comment]
I would suggest starting small - don't aim for all files. And use your best judgement which parts of a file are more important to add tests for. `useful_states.jl`, `classical_register.jl` and `QuantumClifford.jl` seem like good first places. Be sure to search online topics like "what makes a good unit test" and "test driven development" if you have not done this type of development before. I do not use the github assignees functionality - feel free to submit a pull request or ping me with questions in your own fork.

**Comment by Krastanov** [comment]
looking at the test coverage report, most of the code lacking coverage is diagnostic or `Base.show`. Closing this as there is no urgency for test coverage anymore. Additional coverage would of course be appreciated if anyone finds something of note
