### ISSUE TITLE
How to get a maximally mixed state 

### ISSUE THREAD

**Issue by jisutich** [Krastanov/QuantumClifford.jl#51]
Hi,

How to get a maximally mixed state? I think this is a stabilizer state, right? The code `state = one(MixedDestabilier,n,n)` gives me a pure state with all spins up, right? (I apologize if I made mistakes. I am still slowly learning this field). Also, which reference talks about the destabilizers of mixed state? I understand the pure state case but for the mixed state case, it is not quite clear to me. Thanks

**Comment by Krastanov** [comment]
You are right. You can use `one(MixedDestabilizer, 0, n)` to make a tableau of rank 0, i.e. a tableau with no set stabilizers, i.e. a completely mixed stabilizer state. In general you get `one(MixedDestabilizer, rank, nb_of_qubits)`.

The Aaronsons paper https://journals.aps.org/pra/abstract/10.1103/PhysRevA.70.052328 seems to mention mixed states and this paper on the traceout operation also seems to mention them https://iopscience.iop.org/article/10.1088/1367-2630/7/1/170/meta

**Comment by jisutich** [comment]
Got it. Thanks.
