### ISSUE TITLE
add clipping algorithm and bipartite entanglement calculation

### ISSUE THREAD

**Issue by royess** [Krastanov/QuantumClifford.jl#58]
As I mentioned in #57 , I have created a fork <https://github.com/royess/QuantumClifford.jl/tree/dev-clipping> to add clipping algorithm and entanglement entropy calculation. (Ref: Phys. Rev. B 100, 134306 (2019).) And I think it will be great if I can merge them into the original repo.

My implementations allow us to do following things:
1. Clipping algorithm. Briefly speaking, the algorithm can turn a stabilizer state into clipped gauge, where at each qubit the number of left and right endpoints of stabilizers stay are 2. And the two endpoints at each qubit is different Pauli operator. (Ref: Phys. Rev. X 7, 031016 (2017).)
2. Bigram. Based on clipping algorithm, we can collect a table of locations of endpoints, called the bigram. Bigram is unique for a stabilizer state. And the length distribution from bigram also gives some physical information in the first reference paper.
3. Bipartite entanglement entropy. Based on bigram, we can easily calculate bipartite entanglement entropy of a contiguous subregion.

The implementations are tested by random stabilizer states. For entanglement entropy, @Krastanov and I have cross checked with a pure-Julia and a Qiskit implementation.

Besides, as dicussed in #57 , @Krastanov and I proposed three ways (including clipping algorithm) to calculate entanglement entropy. And I think we need find a good way to arrange them.

If @Krastanov agrees, we may dicuss in details about a PR. Thanks!

**Comment by Krastanov** [comment]
Thanks, @royess , this looks wonderful! I gave it a quick read at https://github.com/Krastanov/QuantumClifford.jl/compare/master...royess:dev-clipping and I will need to spend some time reading the shared papers before I can review this. But please, do submit a pull request for it. We will probably need to discuss documentation, and function names, but that would be minor. I would like to review your main implementation in more detail, because it uses a ton of bit-fiddling: it is hard to write code in this style (which I assume you have already discovered ;) so it would be a good idea to at least think how it can be done in a more legible, abstracted away form.

**Comment by royess** [comment]
Thanks! I will prepare a cleaner branch for PR soon. And I would welcome any dicussion. (In this issue, or by the email in my Github profile.)

Besides, I mainly referred to APPENDIX A in Phys. Rev. B 100, 134306 (2019). And I think there is a probably small "bug" in the sketch of "Clipping algorithm part 2" in  APPENDIX A.a of the paper. The authors say: "In doing so, one has to always eliminate the longer stabilizer by the shorter one". But I suppose the correct way is "to always eliminate stabilizer whose left endpoint is more left by stabilizer whose left endpoint is more right". It will be very helpful if you can have a double check when reading the paper.

> so it would be a good idea to at least think how it can be done in a more legible, abstracted away form.

I agree. We have a data structure name `bitset` (https://github.com/JuliaLang/julia/blob/master/base/bitset.jl). I think it may be a good candidate to represent truth tables in our problem.

**Comment by Krastanov** [comment]
Implemented in the now merged #59
