### ISSUE TITLE
canonicalize_clip! for mixed stabilizer states

### ISSUE THREAD

**Issue by gsommers** [Krastanov/QuantumClifford.jl#87]
In the function `canonicalize_clip!`, on line `entanglement.jl`, if you change 
```
 k2 = findfirst(let j=j, k1=k1; k->
                           (|(tab[k,j]...) & # not identity
                           (tab[k,j]!=tab[k1,j])) end, # not same as k1
                           k1+1:columns)
```

to

```
 k2 = findfirst(let j=j, k1=k1; k->
                           (|(tab[k,j]...) & # not identity
                           (tab[k,j]!=tab[k1,j])) end, # not same as k1
                           k1+1:rows)
```
then the clipped gauge construction works for mixed states as well. Then the associated `entanglement_entropy` function needs to be modified (line 188):
```
length(subsystem_range) - count(r->(r[1] in subsystem_range && r[2] in subsystem_range, eachrow(bg))
```

**Comment by Krastanov** [comment]
Thanks! Could you submit this as a pull request?

**Comment by gsommers** [comment]
Sure, I just submitted the request.
I also modified the function `entanglement_entropy(Val(:rref))` to work for mixed states. In the old version it traces out subsystem A and returns the entropy of its complement. This is correct for pure states, since S(A)=S(A^c) in that case, but for mixed states I changed it to trace out the complement.
